export const SET_CURRENT_PAY_ACCOUNT				         = '@current_pay_account/SET_CURRENT_PAY_ACCOUNT'

export const PAY_ACCOUNTS_REQUESTED			             = '@pay_accounts/PAY_ACCOUNTS_REQUESTED_START'
export const PAY_ACCOUNTS_REQUESTED_SUCCESS 	       = '@pay_accounts/PAY_ACCOUNTS_REQUESTED_SUCCESS'
export const PAY_ACCOUNTS_REQUESTED_ERROR 	         = '@pay_accounts/PAY_ACCOUNTS_REQUESTED_ERROR'
export const PAY_ACCOUNT_DELETED                     = '@pay_account/DELETED'
export const PAY_ACCOUNT_DELETED_SUCCESS             = '@pay_account/DELETED_SUCCESS'
export const PAY_ACCOUNT_DELETED_ERROR               = '@pay_account/DELETED_ERROR'
export const PAY_ACCOUNT_CREATE_SUCCESS              = '@pay_account/CREATE_SUCCESS'
export const PAY_ACCOUNT_CREATE_ERROR 			         = '@pay_account/CREATE_ERROR'

export const CREATE_CARD                             = '@pay_account/CREATE_CARD'
export const CREATE_BANK                             = '@pay_account/CREATE_BANK'
export const SET_DEFAULT_ACCOUNT                     = '@pay_account/SET_DEFAULT_ACCOUNT'
export const SET_DEFAULT_ACCOUNT_SUCCESS             = '@pay_account/SET_DEFAULT_ACCOUNT_SUCCESS'
export const SET_DEFAULT_ACCOUNT_ERROR               = '@pay_account/SET_DEFAULT_ACCOUNT_ERROR'
